console.log(" ---------- Returns True ----------\n");
var myName = "Zeeshan";
console.log("Statement: myName = 'Zeeshan'? | Predict: True | Result: ".concat(myName == 'Zeeshan'));
console.log(" ==================== \n");
var nicEligibilityAge = 18;
console.log("Statement: nicEligibilityAge = 18? | Predict: True | Result: ".concat(nicEligibilityAge > 17));
console.log(" ==================== \n");
nicEligibilityAge = 18;
console.log("Statement: if type of nicEligibilityAge variable is 'number'. | Predict: True | Result: ".concat(typeof (nicEligibilityAge) == 'number'));
console.log(" ==================== \n");
var numbers = [1, 2, 3, 4, 5];
console.log(numbers);
console.log(numbers.indexOf(5));
console.log("Statement: Index of element 5 is 4 in array? | Predict: True | Result: ".concat(numbers[3] == numbers.indexOf(5)));
console.log(" ==================== \n");
myName = "Zeeshan";
console.log(myName);
console.log("Statement: If a string is empty? | Predict: True | Result: ".concat(myName.length != 0));
console.log(" ==================== \n");
console.log(" ---------- Returns False ----------\n");
console.log(numbers);
console.log("Statement: If an array is empty | Predict: False | Result: ".concat(numbers.length == 0));
console.log(" ==================== \n");
var onlyNumbers = '2';
console.log(onlyNumbers);
console.log("Type of onlyNumbers variable is ".concat(typeof (onlyNumbers)));
console.log("Statement: If a number is an integer | Predict: False | Result: ".concat(typeof (onlyNumbers) == 'number'));
console.log(" ==================== \n");
var numberInString = '2';
var numberInInteger = 2;
console.log("Value of numberInString var is ".concat(numberInString, " and type of var is ").concat(typeof (numberInString)));
console.log("Value of numberInInteger var is ".concat(numberInInteger, " and type of var is ").concat(typeof (numberInInteger)));
console.log("Statement: If both variables are of the same type | Predict: False | Result: ".concat(typeof (numberInString) == typeof (numberInInteger)));
console.log(" ==================== \n");
var car = 'Honda Civic';
console.log(car);
console.log("Statement: If a Car is Land Cruiser | Predict: False | Result: ".concat(car == "Land Cruiser"));
console.log(" ==================== \n");
var typescriptFact = 'Typescript provides type safety';
console.log("Statement: If 'Typescript' does not provide 'Type Safety' | Predict: False | Result: ".concat(!typescriptFact));
